name: Build
on:
  push:
    branches: [broken-link-checker]
  pull_request:
    branches: [broken-link-checker]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install npm packages
        run: |
          npm ci

      - name: Run npm tests
        run: |
          npm test

      - name: Install bart
        run: |
          curl -LOs https://github.com/fermyon/bartholomew/releases/download/v0.3.0/bart
          chmod +x bart
          mv bart /usr/local/bin

      - name: Check Docs
        run: |
          bart check content/* && bart check content/**/*

      - name: Install spin
        uses: engineerd/configurator@v0.0.8
        with:
          name: "spin"
          url: "https://github.com/fermyon/spin/releases/download/canary/spin-canary-linux-amd64.tar.gz"
          pathInArchive: "spin"

      - name: Check broken links
        run: |
          npm install broken-link-checker -g
          (npm run spin &)
          timeout 60s bash -c 'until curl --silent -f http://localhost:3000 > /dev/null; do sleep 2; done'
          blc --recursive http://127.0.0.1:3000         \
                                                        \
            `## redirects to https://www.<url>`         \
            --exclude 'https://fermyon.com/'            \
            --exclude 'https://fermyon.dev/'            \
            --exclude 'https://www.hashicorp.com/nomad' \
                                                        \
            `## returns 403`                                                                                                                                                                        \
            --exclude 'https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits'                                                                            \
            --exclude 'https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account'                                                    \
            --exclude 'https://docs.github.com/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/remembering-your-github-username-or-email'    \
            --exclude 'https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification'                                                        \
                                                                                                                    \
            `## false positives`                                                                                    \
            --exclude 'https://marketplace.visualstudio.com/items?itemName=fermyon.spin-vscode&ssr=false#overview'  \
            --exclude 'https://marketplace.visualstudio.com/items?itemName=fermyon.autobindle'                      \
            --exclude 'https://crates.io/'                                                                          \
            --exclude 'https://crates.io/crates/bytes'                                                              \
            --exclude 'https://crates.io/crates/http'                                                               \
            --exclude 'https://www.instagram.com/fermyontech/'                                                      \
            --exclude 'https://www.linkedin.com/company/fermyon/'
